export enum AuditAction {
    EMPLOYEE_STATUS_CHANGED = "EMPLOYEE_STATUS_CHANGED",
    EMPLOYEE_SOFT_DELETED = "EMPLOYEE_SOFT_DELETED",
    GOAL_CREATED = "GOAL_CREATED",
    GOAL_UPDATED = "GOAL_UPDATED",
    REVIEW_CREATED = "REVIEW_CREATED",
    LEAVE_APPROVED = "LEAVE_APPROVED",
    LEAVE_REJECTED = "LEAVE_REJECTED",
    COMPENSATION_UPDATED = "COMPENSATION_UPDATED",
    PAYROLL_PROCESSED = "PAYROLL_PROCESSED",
    ATTENDANCE_UPDATED = "ATTENDANCE_UPDATED",
}
